[package]
name = "excali_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21.0"
egui-wgpu = "0.21.0"
egui-winit = "0.21.1"
