[package]
name = "excali_io"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.26.0", default-features = false, features = ["fs", "io-util" ,"rt-multi-thread", "sync"] }
toml = "0.7.2"

[dependencies.serde]
version = "1.0.152"
features = ["derive"]
