[package]
name = "magibreak"
edition = "2021"
version = "0.1.0"

[dependencies]
env_logger = "0.10.0"
gcd = "2.3.0"
log = "0.4.17"
wgpu = "0.15.1"
winit = "0.28.1"
excali_io = { version = "0.1.0", path = "../excali_io", features = ["nalgebra"] }
bytemuck = { version = "1.13.1", features = ["derive"] }
excali_3d = { version = "0.1.0", path = "../excali_3d", features = ["parry3d"] }
rapier3d = { version = "0.17.2", features = ["debug-render"] }

[dependencies.excali_input]
version = "0.1.0"
path = "../excali_input"
features = []

[dependencies.excali_render]
version = "0.1.0"
path = "../excali_render"
features = []

[dependencies.excali_sprite]
version = "0.1.0"
path = "../excali_sprite"
features = []

[dependencies.excali_ui]
version = "0.1.0"
path = "../excali_ui"
features = []

[dependencies.nalgebra]
version = "0.32.1"
features = ["serde-serialize", "std"]
default-features = false

[dependencies.serde]
version = "1.0.152"
features = ["derive"]
