lines = []
cursor = [0, 0]

[sigils."0 0"]
rune = "Alpha"
orb = "Circle"

[sigils."-1 -1"]
rune = "Alpha"
orb = "Circle"

[sigils."1 -1"]
rune = "Alpha"
orb = "Circle"

[sigils."-1 1"]
rune = "Alpha"
orb = "Circle"

[sigils."1 1"]
rune = "Alpha"
orb = "Circle"
