cursor = [0, 0]

[sigils."-2 2"]
rune = "Alpha"
orb = "Circle"

[sigils."2 -2"]
rune = "Alpha"
orb = "Circle"

[sigils."-2 -2"]
rune = "Alpha"
orb = "Circle"

[sigils."0 -2"]
rune = "Alpha"
orb = "Circle"

[sigils."2 2"]
rune = "Alpha"
orb = "Circle"

[sigils."2 0"]
rune = "Alpha"
orb = "Circle"

[sigils."-2 0"]
rune = "Alpha"
orb = "Circle"

[sigils."0 2"]
rune = "Alpha"
orb = "Circle"

[sigils."0 0"]
rune = "Alpha"
orb = "Circle"

[[lines]]
start = [-1, -1]
end = [3, -1]

[[lines]]
start = [1, 1]
end = [1, -2]
