cursor = [0, 0]

[sigils."0 0"]
rune = "Sigma"
orb = "Diamond"

[sigils."0 2"]
rune = "Alpha"
orb = "Circle"

[sigils."-2 0"]
rune = "Alpha"
orb = "Circle"

[sigils."2 -2"]
rune = "Alpha"
orb = "Diamond"

[sigils."-2 -2"]
rune = "Alpha"
orb = "Circle"

[sigils."0 -2"]
rune = "Alpha"
orb = "Circle"

[sigils."2 2"]
rune = "Alpha"
orb = "Circle"

[sigils."-2 2"]
rune = "Alpha"
orb = "Diamond"

[sigils."2 0"]
rune = "Alpha"
orb = "Circle"

[[lines]]
start = [1, 2]
end = [1, -2]

[[lines]]
start = [-1, 2]
end = [-1, -2]

[[lines]]
start = [-2, -1]
end = [2, -1]

[[lines]]
start = [2, 1]
end = [-2, 1]

[[lines]]
start = [1, -2]
end = [1, 2]

[[lines]]
start = [-2, 1]
end = [2, 1]

[[lines]]
start = [-1, -2]
end = [-1, 2]

[[lines]]
start = [2, -1]
end = [-2, -1]
