lines = []
cursor = [0, 0]

[runes."0 -2"]
sigil = "Sigma"
orb = "Octogon"

[runes."2 0"]
sigil = "Sigma"
orb = "Circle"

[runes."0 2"]
sigil = "Sigma"
orb = "Octogon"

[runes."0 0"]
sigil = "Sigma"
orb = "Circle"
