lines = []
cursor = [0, 0]

[sigils."0 0"]
rune = "Alpha"
orb = "Circle"

[sigils."-2 1"]
rune = "Sigma"
orb = "Octogon"

[sigils."0 -2"]
rune = "Alpha"
orb = "Circle"

[sigils."2 1"]
rune = "Alpha"
orb = "Circle"
