lines = []
cursor = [0, 0]

[sigils."-1 1"]
rune = "Sigma"
orb = "Octogon"

[sigils."1 1"]
rune = "Sigma"
orb = "Octogon"

[sigils."0 0"]
rune = "Alpha"
orb = "Circle"

[sigils."0 -1"]
rune = "Alpha"
orb = "Circle"

[sigils."2 1"]
rune = "Alpha"
orb = "Circle"
