lines = []
cursor = [0, 0]

[runes."0 0"]
sigil = "Alpha"
orb = "Circle"

[runes."-1 1"]
sigil = "Sigma"
orb = "Diamond"

[runes."0 1"]
sigil = "Phi"
orb = "Circle"

[runes."0 2"]
sigil = "Alpha"
orb = "Octogon"
