cursor = [0, 0]

[sigils."2 1"]
rune = "Sigma"
orb = "Circle"

[sigils."0 0"]
rune = "Alpha"
orb = "Circle"

[sigils."-1 1"]
rune = "Phi"
orb = "Circle"

[sigils."-1 -1"]
rune = "Phi"
orb = "Circle"

[sigils."1 1"]
rune = "Phi"
orb = "Circle"

[sigils."2 -1"]
rune = "Sigma"
orb = "Circle"

[sigils."0 2"]
rune = "Alpha"
orb = "Diamond"

[sigils."0 1"]
rune = "Phi"
orb = "Circle"

[sigils."-2 1"]
rune = "Sigma"
orb = "Circle"

[sigils."-2 0"]
rune = "Alpha"
orb = "Diamond"

[sigils."0 -2"]
rune = "Alpha"
orb = "Diamond"

[sigils."1 0"]
rune = "Phi"
orb = "Circle"

[sigils."-1 2"]
rune = "Sigma"
orb = "Circle"

[sigils."1 2"]
rune = "Sigma"
orb = "Circle"

[sigils."0 -1"]
rune = "Phi"
orb = "Circle"

[sigils."2 0"]
rune = "Alpha"
orb = "Diamond"

[sigils."-1 -2"]
rune = "Sigma"
orb = "Circle"

[sigils."-1 0"]
rune = "Phi"
orb = "Circle"

[sigils."1 -2"]
rune = "Sigma"
orb = "Circle"

[sigils."-2 -1"]
rune = "Sigma"
orb = "Circle"

[sigils."1 -1"]
rune = "Phi"
orb = "Circle"

[[lines]]
start = [0, 3]
end = [2, -2]

[[lines]]
start = [0, 3]
end = [-2, -2]
