lines = []
cursor = [0, 0]

[runes."0 1"]
sigil = "Alpha"
orb = "Circle"

[runes."1 0"]
sigil = "Alpha"
orb = "Circle"

[runes."-1 0"]
sigil = "Alpha"
orb = "Circle"

[runes."0 0"]
sigil = "Sigma"
orb = "Circle"

[runes."0 -1"]
sigil = "Alpha"
orb = "Circle"
