[package]
name = "excali_sprite"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.15.1"
bytemuck = { verstion = "1.13.0", features = ["derive"] }
nalgebra = { version = "0.32.1", default-features = false, features = ["serde-serialize"] }
