[package]
name = "excali_sprite"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { verstion = "1.13.0", features = ["derive"] }
excali_render = { version = "0.1.0", path = "../excali_render" }
nalgebra = { version = "0.32.1", default-features = false, features = ["serde-serialize"] }
